name: 'Build Zweep'
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["cradio_left","cradio_right"]'
      alphas: 'Colemak'
      nav: 'invertedT'
      clipboard: 'default'
      layers: 'default'
      mapping: 'default'
      custom_config: 'default'
      kconfig: 'default'
      branches: 'default'